
const GET_SELLER="GET_SELLER"
const SHOW_DETAIL="SHOW_DETAIL"
const HIDE_DETAIL="HIDE_DETAIL"
const GET_GOODS='GET_GOODS'
const GET_RATINGS='GET_RATINGS'
const SHOWLIST = 'SHOWLIST'
const HIDELIST = 'HIDELIST'
const SHOWFOOTERLIST = 'SHOWFOOTERLIST'
const HIDEFOOTERLIST = 'HIDEFOOTERLIST'


export default {
	GET_SELLER,
	SHOW_DETAIL,
	HIDE_DETAIL,
	GET_GOODS,
	GET_RATINGS,
	SHOWLIST,
	HIDELIST,
	SHOWFOOTERLIST,
	HIDEFOOTERLIST
}